# Problema 2

Considere el espacio de Hilbert $\mathscr{M}_4(\mathbb{C})$, con el producto interno estudiado en clase. Además las
matrices:

$$
\gamma_1=
\begin{pmatrix}
0 & 0 & 0 & -i\\
0 & 0 & -i & 0\\
0 & i & 0 & 0\\
i & 0 & 0 & 0\\
\end{pmatrix},
\hspace{1cm}
\gamma_2=
\begin{pmatrix}
0 & 0 & 0 & -1\\
0 & 0 & 1 & 0\\
0 & 1 & 0 & 0\\
-1 & 0 & 0 & 0\\
\end{pmatrix}
\hspace{1cm}
\gamma_3=
\begin{pmatrix}
0 & 0 & -i & 0\\
0 & 0 & 0 & i\\
i & 0 & 0 & 0\\
0 & -i & 0 & 0\\
\end{pmatrix}
\hspace{1cm}
\gamma_4=
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & -1 & 0\\
0 & 0 & 0 & -1\\
\end{pmatrix}
\hspace{1cm}
\gamma_5=
\begin{pmatrix}
0 & 0 & -1 & 0\\
0 & 0 & 0 & -1\\
-1 & 0 & 0 & 0\\
0 & -1 & 0 & 0\\
\end{pmatrix}
$$

Además considere la definición de las matrices:
$$
\sigma_{jk} = \frac{i}{2}[\gamma_j,\gamma_k],
$$

con $j < k$, $j = 1, 2, 3$ y $k = 2, 3, 4$.

## A: 

Calcule $\sigma{12}$, $\sigma{13}$, $\sigma{14}$, $\sigma{23}$, $\sigma{24}$ y $\sigma{34}$.

### Solución:

Importo librerías:

In [1]:
import numpy as np
import qutip as qt

Defino las matrices "$\gamma$" y las guardo en un arreglo para acceder a ellas iterativamente

In [2]:
gamma1 = qt.Qobj([[0,0,0,-1j],
                   [0,0,-1j,0],
                   [0,1j,0,0],
                   [1j,0,0,0]])

gamma2 = qt.Qobj([[0,0,0,-1],
                   [0,0,1,0],
                   [0,1,0,0],
                   [-1,0,0,0]])

gamma3 = qt.Qobj([[0,0,-1j,0],
                   [0,0,0,1j],
                   [1j,0,0,0],
                   [0,-1j,0,0]])

gamma4 = qt.Qobj([[1,0,0,0],
                   [0,1,0,0],
                   [0,0,-1,0],
                   [0,0,0,-1]])

gamma5 = qt.Qobj([[0,0,-1,0],
                   [0,0,0,-1],
                   [-1,0,0,0],
                   [0,-1,0,0]])

gammas = [gamma1,gamma2,gamma3,gamma4,gamma5]

Defino la función ``Sigma`` para calcular los $\sigma_{jk}$
$$
\sigma_{jk} = \frac{i}{2}[\gamma_j,\gamma_k]
$$
Esta función recibe los índices ``j``,  ``k`` y las matrices "$\gamma$" dentro de un arreglo, por esto fue que anteriormente guardamos las matrices en un arreglo. 

In [3]:
def Sigma(j, k, gammas):
    return (1j/2) * qt.commutator(gammas[j-1], gammas[k-1])

Ahora solo llamamos a la función sigma iterativamente con los ``j`` y ``k`` deseados:

In [4]:
for j in range(1, 4):
    for k in range(j+1, 5):
        print(f"sigma{j}{k}:\n", Sigma(j, k, gammas), "\n")

sigma12:
 Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]] 

sigma13:
 Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.+0.j -0.-1.j  0.+0.j  0.+0.j]
 [ 0.+1.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -0.-1.j]
 [ 0.+0.j  0.+0.j  0.+1.j  0.+0.j]] 

sigma14:
 Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.  0.  0. -1.]
 [ 0.  0. -1.  0.]
 [ 0. -1.  0.  0.]
 [-1.  0.  0.  0.]] 

sigma23:
 Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0. -1.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0. -1.  0.]] 

sigma24:
 Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.+0.j  0.+0.j  0.+0.j  0.+1.j]
 [ 0.+0.j  0.+0.j -0.-1.j  0.+0.j]
 [ 0.+0.j  0.+1

Obtuvimos:
$$
\sigma_{12}=
\begin{pmatrix}
-1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & -1 & 0\\
0 & 0 & 0 & 1\\
\end{pmatrix},
\hspace{0.7cm}
\sigma_{13}=
\begin{pmatrix}
0 & -i & 0 & 0\\
i & 0 & 0 & 0\\
0 & 0 & 0 & -i\\
0 & 0 & i & 0\\
\end{pmatrix},
\hspace{0.7cm}
\sigma_{14}=
\begin{pmatrix}
0 & 0 & 0 & -1\\
0 & 0 & -1 & 0\\
0 & -1 & 0 & 0\\
-1 & 0 & 0 & 0\\
\end{pmatrix},
$$

$$
\sigma_{23}=
\begin{pmatrix}
0 & -1 & 0 & 0\\
-1 & 0 & 0 & 0\\
0 & 0 & 0 & -1\\
0 & 0 & -1 & 0\\
\end{pmatrix},
\hspace{0.7cm}
\sigma_{24}=
\begin{pmatrix}
0 & 0 & 0 & i\\
0 & 0 & -i & 0\\
0 & i & 0 & 0\\
-i & 0 & 0 & 0\\
\end{pmatrix},
\hspace{0.7cm}
\sigma_{34}=
\begin{pmatrix}
0 & 0 & -1 & 0\\
0 & 0 & 0 & 1\\
-1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
\end{pmatrix}
$$

## B:

Considere el conjunto de matrices { $\mathbb{I}_4, γ_1, γ_2, γ_3, γ_4, γ_5, γ_5γ_1, γ_5γ_2, γ_5γ_3, γ_5γ_4, σ_{12}, σ_{13}, σ_{14}, σ_{23}, σ_{24}, σ_{34}$ }

Demuestre que el conjunto anterior es una base de este espacio.

### Solución:

Primero creamos el arreglo ``basis`` para almacenar el conjunto, inicializamos ``basis`` con las matrices que conocemos: { $\mathbb{I}_4, γ_1, γ_2, γ_3, γ_4, γ_5$ }. Luego añadimos al arreglo las matrices $\gamma_{5i}$ con $i=1,2,3,4$. Y para terminar de completar el conjunto, con ayuda de la función ``Sigma`` calculamos y añadimos { $σ_{12}, σ_{13}, σ_{14}, σ_{23}, σ_{24}, σ_{34}$ }

In [5]:
qt.qeye(4)

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dia, isherm=True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [6]:
basis = [qt.qeye(4),gamma1,gamma2,gamma3,gamma4,gamma5]

for i in range(4):
    basis.append(gammas[4] * gammas[i])

for j in range(1, 4):
    for k in range(j+1, 5):
        basis.append(Sigma(j, k, gammas))

Ahora para comprobar que el conjunto es una base, debemos verificar que el producto interno entre diferentes elementos del conjunto da $\mathbf{0}$ y que el producto interno entre el mismo elemento es un finito y diferente de $\mathbf{0}$

Para esto recordamos el producto interno entre matrices:
$$
<A|B> = Tr(A^\dagger B)
$$

In [7]:
def InnerProd(A, B):
    return (A.dag() * B).tr()

Ahora definimos la función ``IsBasis`` para verificar si un conjunto de matrices es una base de la siguiente forma:

Recorremos el conjunto con dos índices y realizamos el producto interno entre los elementos correspondientes a ``i`` y ``j``. Si ``i=j`` y el producto punto es nulo significa que el conjunto NO es base. Si ``i!=j`` y el producto interno es diferente de $\mathbf{0}$ también significa que el conjunto NO es base. Si se recorre todo el conjunto y estos casos no se presentan, significa que el conjunto SI es base.

In [8]:
def IsBasis(basis):
    for i in range(len(basis)):
        for j in range(len(basis)):
            inner = InnerProd(basis[i], basis[j])

            if i == j and inner == 0:
                print(f"\n no es base por a{i}{j}")
                break
            elif i != j and inner != 0:
                print(f"\n no es base por b{i}{j}")
                break

    print("Si es base")

Por último solo nos queda llamar la función ``IsBasis`` pasandole el conjunto ``basis``

In [9]:
IsBasis(basis)

Si es base


Con esto queda verificado.

## C:

Es una base ortogonal? ¿Ortonormal?

### Solución:

Para saber si es ortogonal o ortonormal, tenemos que fijarnos en la norma, es decir, en la raíz cuadrada del producto interno entre el mismo elemento de la base:
$$
|A| = \sqrt{Tr(A^\dagger A)}
$$
Para esto podemos modificar ligeramente la función ``IsBasis`` para que además de indicarnos si el conjunto es base, nos indique la norma cuando ``i=j`` y así verificar la norma para todos los elementos.

In [10]:
def IsBasis_Norm(basis):
    for i in range(len(basis)):
        for j in range(len(basis)):
            inner = InnerProd(basis[i], basis[j])

            if i == j and inner == 0:
                print(f"\n no es base por a{i}{j}")
                break
            elif i != j and inner != 0:
                print(f"\n no es base por b{i}{j}")
                break
            elif i == j:
                print(np.sqrt(inner))

    print("Si es base")

In [11]:
IsBasis_Norm(basis)

2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
Si es base


Al llamar a la función podemos ver que la norma es "$2$", para que la base sea ortonormal la norma debe ser "$1$", por lo que la base es ortogonal, NO ortonormal.